### PR TITLE
Encode URIs properly and use new sharing URL

### LINKED ISSUE #161: Impossible to activate the Gallery
Hello! I have tried to install the last stable Gallery version (8.0.11). After an Apache restart, Gallery appears in inactive apps. But clicking on "activate" button is not efficient, the apps remains inactive (the apps seems to be active after a click, but after a refresh, the button "activate" appears again).

My configuration
MySQL 5.5.4.3
Apache 2.4.7

Do you have any idea?

Thanxx

Gringo1er

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/gallery/issues/161, I also switched to the new sharing URL here.

@icewind1991 @karlitschek Please test

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1: please backport

**Comment by LukasReschke** [comment]
https://github.com/owncloud/gallery/compare/720f9173f7...0b5bfe6b60

**Comment by oparoz** [comment]
I think you might have missed this one: https://github.com/owncloud/gallery/blob/master/js/album.js#L246

**Comment by oparoz** [comment]
And this one: https://github.com/owncloud/gallery/blob/master/js/gallery.js#L202

**Comment by LukasReschke** [comment]
Mind to create a pull request? ;-)

(that said - such folders work fine here :))

**Comment by oparoz** [comment]
Let's see if you can reproduce the problem. I haven't tested on that version of the app.

Things break when I have folders or files with special characters in their name.
Starting at the bottom of
`Folder éà/Folder +%&/Folder ;.jpg`

Clicking on the `Folder +%&` bread crumb breaks the app

Now if you have a file named `+& pin ; OK.png` you might run into problems, either when asking for the preview or refreshing the preview (F5).

Let me know how it goes :)

**Pull request merged**
