### PR TITLE
use aspect preserving previews from core to load images in slideshow wit...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...h lower resolution to optimize user experience

requires https://github.com/owncloud/core/pull/8407 to be merged first

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jancborchardt @icewind1991 @karlitschek @PVince81 THX

**Comment by karlitschek** [comment]
Nice :+1:

**Comment by PVince81** [comment]
:+1: works well (had the other branch checked out from core). Tested with wide panoramic pics.
Let's wait for that one to be merged first.

**Comment by jancborchardt** [comment]
owncloud/core#8407 merged, let’s merge this one then.

**Comment by DeepDiver1975** [comment]
I'll prepare a second pull request to use document width in here as well

**Pull request merged**
