### PR TITLE
Infinite scrolling for gallery + seamless layout

### PR DESCRIPTION
**Pull request by jbtbnl**
This is a work in progress of @icewind1991 regarding https://github.com/owncloud/gallery/issues/5 and a successor of my seamless layout in https://github.com/owncloud/gallery/pull/17

### CODE REVIEW

**Comment by jancborchardt** [comment]
@icewind1991 would have been cooler to have it split up in several commits to actually see what has been done. ;) Also, to have @jbtbnl’s commits separate for proper credit.

**Comment by jbtbnl** [comment]
Yeah, too bad that my code wasn't used. Anyway, good luck with it :wink:

**Comment by jancborchardt** [comment]
@jbtbnl are you ok with the layout though, is it what you had in mind as well?

**Comment by jbtbnl** [comment]
@jancborchardt the design is basically the same but there are a few issues with the implementation of @icewind1991:
- [x] the last row contains more images then visible
- [x] window resize isn't handled
- [x] the captions on albums are not dynamically centered

Also the preview images are loading way to slow (same issue in my branch as well).

**Comment by jbtbnl** [comment]
- [x] horizontal scaling doesn't work properly

**Comment by icewind1991** [comment]
Added support for window resizing, fixed centering of captions and improved performance by loading thumbnails in parallel. I think this is ready for testing (cc @jancborchardt @PVince81 @karlitschek @DeepDiver1975)

@jbtbnl Not sure what you mean with "the last row contains more images then visible" and "horizontal scaling doesn't work properly"

**Comment by LukasReschke** [comment]
- [x] Long folder names ("titles") do overlap the preview image instead of being cropped with "..." or so
- [x] Share button does not work for me showing `Uncaught TypeError: Cannot read property 'viewedItems' of undefined` in gallery.js:161

**Comment by LukasReschke** [comment]
Otherwise: Works and looks great.

**Comment by LukasReschke** [comment]
Another one:
- [x] When clicking on a folder that only contains another subfolder and then going back to the previous folder the subfolder is not shown anymore.

**Comment by icewind1991** [comment]
@LukasReschke fixed the issues, thanks for testing

**Comment by LukasReschke** [comment]
I do have another problem with large panoramic photos. Some photos are still not shown since the images are too wide for the row.

Files:
screen shot 2014-05-25 at 18 45 54

Gallery view:
screen shot 2014-05-25 at 18 44 01

The images used in this album are downloadable here until 01.06.2014: https://cloud.statuscode.ch/public.php?service=files&t=48ab5132bd4d002605398c7950562992

**Comment by LukasReschke** [comment]
Also the public share view seems not to work ~~properly~~ at all.

**Comment by jbtbnl** [comment]
@icewind1991 the screenshots of @LukasReschke show what I meant with

> the last row contains more images then visible

**Comment by LukasReschke** [comment]
Gnah. Sorry, public download doesn't work anymore since I somehow triggered a bug in core that leads to file loss :-/

Trying to reproduce....

**Comment by icewind1991** [comment]
Fixed the issue with very wide images, also limited the aspect ratio of thumbnails to 3:1

**Comment by LukasReschke** [comment]
Works after clearing the previews. Thanks a lot.

I'll look into sharing.

**Comment by LukasReschke** [comment]
Sharing should now work properly in subfolders, @icewind1991 can you please review my commits?

**Comment by icewind1991** [comment]
@LukasReschke changes look good

**Comment by jancborchardt** [comment]
The outline stuff looks quite strange. I needed to double check if it was a glitch or something.

What would be better is simply 2px separation between everything. 2px to the side and the top, 2px between every image, and 2px between each row. It needs to be 2 px everywhere to look consistent – it can vary at the right though.

**Comment by jancborchardt** [comment]
I mean 4px, not 2px. :)

**Comment by icewind1991** [comment]
I don't like having "whitespace" between the images, especially on mobile I think a seamless layout looks better

**Comment by jancborchardt** [comment]
It makes the pictures blend together. You don’t know where one picture ends and the other continues. Especially when they are similar, this is jarring.

This is not about personal preference after all ;) There’s a reason why Flickr and Dropbox and others have slight space between the pictures. It helps you tell them apart.

**Comment by LukasReschke** [comment]
Three other bugs:
- [ ] When scrolling down on a large gallery and then clicking on a image and closing it the browser is jumped to the top.
- [ ] When sharing a gallery and then directly linking to an image (t=token#Photo.jpg) the gallery isn't shown
- [ ] Directly linking to an image (#photo.jpg) does not work.

Regarding the whitespace: The little black border is already enough for me. I can easily distinguish the pictures.

**Comment by jbtbnl** [comment]
> When scrolling down on a large gallery and then clicking on a image and closing it the browser is jumped to the top.

@LukasReschke fix is here: https://github.com/owncloud/gallery/pull/17/files#diff-721c4fdccbf9e7c9a389daf09b558bfcL378

**Comment by LukasReschke** [comment]
@jbtbnl Could you please commit this to this branch? That would be great!

**Comment by jbtbnl** [comment]
@LukasReschke it seems the fix is already present: https://github.com/owncloud/gallery/pull/28/files#diff-721c4fdccbf9e7c9a389daf09b558bfcL375

Not sure why your issue still exists...

**Comment by jancborchardt** [comment]
Nice, looking way better now! Thank you @jbtbnl @icewind1991! :)

We can fix all the other issues after this, we need to take care not to make pull requests too big. :+1:

**Comment by jancborchardt** [comment]
@icewind1991 now to fixing the way folders are displayed ;)

**Pull request merged**
