### PR TITLE
Preview Images 1-2-3-4 Pics [Fixed]

### PR DESCRIPTION
**Pull request by libasys**
Filling the album preview respecting ratio with
1 Pic = 200 x200
2 Pics = 100 x 200
3 Pics = 100 x 200 / 100 x 100
4 Pics = 100 x 100

### CODE REVIEW

**Comment by libasys** [comment]
1-2-3-4-new

**Comment by jancborchardt** [comment]
@icewind1991 @jbtbnl @requist @DeepDiver1975 @MorrisJobke check this out!

**Comment by jancborchardt** [comment]
@libasys still the same issue as mentioned in #81: for the square ones the aspect ratio is ok. But for the 100*200 ones, they are stretched wide.

Try it out with pictures of people and you will directly see the strange effect.

(Btw, would be cool if everything would be one clean commit. Then it’s also easier to backport. :)

**Comment by jancborchardt** [comment]
@libasys any update here?

**Comment by jospoortvliet** [comment]
Oh, this looks super cool ;-)

**Comment by jancborchardt** [comment]
Yeah, so @libasys is there any update on this?

Or can anyone pick this up? @icewind1991 @owncloud/designers @wakeup?

**Comment by libasys** [comment]
not at the moment, i have to wait for this issue https://github.com/owncloud/gallery/issues/106

**Comment by DeepDiver1975** [comment]
@libasys #106 has been merged - can you please rebase? THX

**Comment by libasys** [comment]
I have a problem with stretching sideeffects for 2 or 3 pics preview of a folder.
@DeepDiver1975 some ideas, how to fix this sideeffect?

Take a look here to see what i mean:

https://ssl.webpack.de/demo70.libasyscloud.de/owncloud/index.php/apps/gallery/public/1c17af51f8e6e9d3039faba4106d8fdb

**Comment by DeepDiver1975** [comment]
> I have a problem with stretching sideeffects for 2 or 3 pics preview of a folder.
> @DeepDiver1975 some ideas, how to fix this sideeffect?

hmmm - we would need to cut the image in this case I guess ...

I'd honestly be okay to merge the current state and fix this side effect in a second pr.
This is a cool enhancement and we should really get this in.

@jancborchardt @icewind1991 objections? THX

**Comment by jancborchardt** [comment]
We already have the multiple files preview in the Pictures app. This specific fix is only about fixing it when there are 2 or 3 images in the folder. (So the 2 or 3 fill the square.) So this should be without side effects.

**Comment by DeepDiver1975** [comment]
> We already have the multiple files preview in the Pictures app. This specific fix is only about fixing it when there are 2 or 3 images in the folder. (So the 2 or 3 fill the square.) So this should be without side effects.

Oh - I see - sorry for the noise

**Comment by oparoz** [comment]
Some of the stretching problems come from core. The Preview class will not properly resize a picture if one of the dimension is smaller than what is asked.
Original: 200x50
Asked: 100x100
**Preview: 200x50
Cached as: 100x100**
That's just plain wrong
OR
Original: 200x100
Asked: 200x200
Preview: 200x100
Cached as: 200x200
A bestfit method should be used to return a 200x200 picture 

Both these examples break the Gallery app as album thumbnails sizes can't be calculated properly any more.
The 2nd problem regarding stretching can be avoided if we put the images in the CSS. It's not a good idea to do it for all images since that's the app's main content, but should be OK for the album "representations".

**Comment by jancborchardt** [comment]
@georgehrke can you fix the preview class as @oparoz mentioned? ^

**Comment by oparoz** [comment]
@jancborchardt - What do you think about using `background-image` for the albums?
I've also noticed that @libasys is going with a different approach: https://github.com/libasys/ownCloud-7.0.3/blob/master/apps/gallery/js/album.js#L45

**Comment by jancborchardt** [comment]
@oparoz as the important thing for the albums is the name and not the image, using `background-image` sounds fine as well.

**Comment by oparoz** [comment]
Pictures are no longer squeezed or distorted
Screenshot

**Comment by jancborchardt** [comment]
Oh, nice! Is there a pull request with that so we can review?

**Comment by oparoz** [comment]
@jancborchardt - Since it requires elements only available in the rewrite, it can't easily be backported. There will always be problems.

It's available live in the [demo](https://oc7demo.interfacloud.com/index.php/apps/galleryplus/public?token=312b038d3e70877199a4d66abf37bdd0) and the [source code for OC7](https://github.com/interfasys/galleryplus/tree/stable7) is now finally available.
Much of the Javascript is the same, so it should be easy to understand how I did it.

**Comment by jancborchardt** [comment]
> Since it requires elements only available in the rewrite, it can't easily be backported. There will always be problems.

Can you be specific about this? It’s a bit sad to see the Gallery being forked, especially since it’s such a simple app. We need to focus our efforts on creating one good Gallery app instead of diverting …

**Comment by oparoz** [comment]
It's not a fork, the PHP rewrite has to happen as the app is
not part of core anymore.
It's a waste of time to keep patching the old version with all its
duplicated code. I've seen it when adding support for lots of media types
in the old version the app should be easier to test as well. 
The goal is to switch PHP base while using the same JS. I was able to
easily merge or add the PRS from here.

As for the previews generator. It's broken in OC7, so ‎I had to add some
PHP code to fix that. With the new JS code added today, I might be able to
get rid of some of it. We still need to repair the cache per example since
it contains the wrong preview.

**Comment by oparoz** [comment]
Let's close this as it's already been implemented in Gallery.

**Comment by jancborchardt** [comment]
Yup :) and it looks pretty awesome man!

**Pull request closed without merging**
