### PR TITLE
oc:// stream wrapper cannot be used to read exif data from the image - u...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...sing \OC\Files\View::getLocalFile

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jancborchardt @icewind1991 @karlitschek @PVince81 THX

**Comment by PVince81** [comment]
Excellent. I meant to fix this eventually but you were fast :smile: 
Going to test this, it usually failed with encryption.
Let me find the ticket.

**Comment by karlitschek** [comment]
Nice :+1:

**Comment by PVince81** [comment]
CC @dttpy

**Comment by PVince81** [comment]
This doesn't seem to work. Not sure what exact test case it covers ?

My steps:
1. Enable encryption
2. Upload non-rotated pic with correct exif data
3. Click on "Pictures"
4. Click on the pic to view it

The picture is never rotated.
I tried putting a breakpoint on the modified code and it doesn't seem to go there.

Is this specific for the public sharing maybe ?

**Comment by DeepDiver1975** [comment]
> 1. Enable encryption

I'll retest with enabled encryption - thx

**Comment by DeepDiver1975** [comment]
Well exif_read_data requires a physical file to operate on and in case of encryption being enabled we don't have this. We could create a unencrypted file but i don't really like this idea.
An alternative approach might be to search for an exif reading method which works properly on stream wrappers or resources.

like https://github.com/sketchbook/xe/blob/master/addons/exif/phpexifrw/exifReader.php

**Comment by DeepDiver1975** [comment]
> I tried putting a breakpoint on the modified code and it doesn't seem to go there.

did you clear the thumbnail cache of the user?

**Comment by PVince81** [comment]
I'm wonder, I thought `getLocalFile()` would create a temporary unencrypted file for that.
For external storages, calling `getLocalFile()` will do the same by downloading the file from the remote storage.

I'll double check that. (and clear the cache furiously)

**Comment by PVince81** [comment]
Ok, I managed to debug this case. It seems that in the case of encryption `getLocalFile()` doesn't return an unencrypted file, so let's leave it.

I'll retest this with ext storage instead.

**Comment by PVince81** [comment]
CC @schiesbn

**Comment by PVince81** [comment]
Switching to use a library that supports reading from stream wrappers could be cool, would make it work with encryption and would also improve the performance with ext storage. (CC @georgehrke)

Tested with ext storage: :+1: pictures/thumbnails are rotated correctly

**Comment by DeepDiver1975** [comment]
I guess this is worth backporting to fix this in 6.0.4? @icewind1991 @karlitschek @PVince81

**Comment by PVince81** [comment]
Yeah, a backport makes sense I think.

**Comment by karlitschek** [comment]
Yes. There should be minimal risk. backport please

**Pull request merged**
