### PR TITLE
fix position of pause icon

### PR DESCRIPTION
**Pull request by MorrisJobke**
Before
pause-icon-before
After
pause-icon-after

Needs backport to stable7 cc @owncloud/designers @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
yes please :+1:

**Comment by jancborchardt** [comment]
Weird, how did that get shifted?

This fixes it in both Firefox and Chrome :+1: good catch @MorrisJobke! :)

**Comment by jancborchardt** [comment]
Backported 54e2327

**Comment by MorrisJobke** [comment]
@jancborchardt and I also tested IE9 ;)

**Pull request merged**
