### PR TITLE
Download button in public gallery

### PR DESCRIPTION
**Pull request by gjedeer**
Issue #33

### CODE REVIEW

**Comment by oparoz** [comment]
It's been implemented in the Gallery rewrite.

You can see what it looks like in the [demo](https://oc7demo.interfacloud.com/index.php/apps/galleryplus/public?token=312b038d3e70877199a4d66abf37bdd0) and the [source code for OC7](https://github.com/interfasys/galleryplus/tree/stable7) is now finally available.

**Comment by gjedeer** [comment]
I'm using ownCloud 7.0.3 (stable) and the download button is still not there.

**Comment by oparoz** [comment]
It's only available in Gallery+ right now:
https://github.com/interfasys/galleryplus/releases

**Comment by DeepDiver1975** [comment]
@jancborchardt @icewind1991 please review and merge - THX

**Comment by icewind1991** [comment]
The generated download link is broken for me "http://localhost/owncloud/s&t=PiJbDx50PianX4c&download&path="

**Comment by gjedeer** [comment]
The code is copied from Files app in owncloud 7.0 and may need updating for other versions. Works fine on 7.0.3 - generated link: https://domain/public.php?service=files&t=5c2080c18a0587acf1cd88f354b861db&download&path=

**Comment by jancborchardt** [comment]
@interfasys @oparoz @icewind1991 since a lot of times I read »this is fixed in the Gallery rewrite« please make a concerted effort to get that merged into the official Gallery app / replace it. Can you do that?

**Comment by oparoz** [comment]
@jancborchardt - I'm all for it and ready to take some time to go through the changes and to answer any question since it's not a simple PR, but I have no clue on how to proceed. Tickets requesting the change are open, @icewind1991 has mentioned he was looking for new maintainers, but I assumed everybody got really busy with the launch of oC8 and that this needed to wait.

**Comment by jospoortvliet** [comment]
@oparoz that would be https://github.com/owncloud/gallery/issues/151 right? @jancborchardt fyi

**Comment by oparoz** [comment]
That's correct @jospoortvliet

**Comment by oparoz** [comment]
Available in [Gallery](https://github.com/owncloud/gallery)

**Pull request closed without merging**
