### PR TITLE
Sample Do not delete

### PR DESCRIPTION
**Pull request by nickvergessen**
- [ ] Depends on https://github.com/owncloud/core/pull/15073

### CODE REVIEW

**Comment by oparoz** [comment]
Is this 8.1 only?

**Comment by nickvergessen** [comment]
Added the core PR to the description. I hope we get it for 8.2, but not going to happen for 8.0 and 8.1

**Comment by oparoz** [comment]
Thanks!

**Comment by oparoz** [comment]
The branch has been added to https://github.com/owncloud/galleryplus/branches for 8.2, so closing here

**Pull request closed without merging**
