### PR TITLE
Preview Images 1-2-3-4 Pics

### PR DESCRIPTION
**Pull request by libasys**
Filling the album preview respecting ratio with 
1 Pic = 200 x200
2 Pics = 100 x 200
3 Pics = 100 x 200 / 100 x 100
4 Pics = 100 x 100

Have fun

### CODE REVIEW

**Comment by jancborchardt** [comment]
@icewind1991 @jbtbnl @requist @DeepDiver1975 @MorrisJobke check this out!

@libasys your contributions are awesome! You should submit pull requests more often! :)

**Comment by jancborchardt** [comment]
@libasys only one issue: for the square ones the aspect ratio is ok. But for the 100*200 ones, they are stretched wide. Can you fix that?

**Comment by libasys** [comment]
this is not ready to merge, i have found a side effect and a problem with square!
Thanks

**Comment by libasys** [comment]
i close this PR and open a new one with the correct working files!

**Comment by jancborchardt** [comment]
You also need to let us know when the new pull request is ready ;) everyone, check out https://github.com/owncloud/gallery/pull/82

**Pull request closed without merging**
