### PR TITLE
show loading spinner instead of static 'Loading' text

### PR DESCRIPTION
**Pull request by jancborchardt**
Make it consistent with other apps.

Please review @libasys @icewind1991 @owncloud/designers

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by karlitschek** [comment]
great :+1:

**Comment by DeepDiver1975** [comment]
:+1: tested

**Comment by jancborchardt** [comment]
@karlitschek I’d like to backport this as well. Ok?

**Comment by karlitschek** [comment]
yes please :-)

**Comment by jancborchardt** [comment]
Backported as 80b033a

**Pull request merged**
