### PR TITLE
mobile: use also for logged-in pictures app. Blocked by core work still

### PR DESCRIPTION
**Pull request by jancborchardt**
This needs https://github.com/owncloud/core/pull/7724 to be merged first and look good, mainly because of the app navigation.

As a basic first step, I just adapted the styles for the mobile share page. Please check @DeepDiver1975 @PVince81 @karlitschek

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please review now as https://github.com/owncloud/core/pull/7724 is merged. :) cc @owncloud/designers

**Comment by tomneedham** [comment]
@jancborchardt What exactly are we looking for / testing?

**Comment by jancborchardt** [comment]
The Pictures app (when logged in) to work nicely on mobile / small screens. That is, mostly the layout should be good and the share dropdown needs to work.

**Comment by tomneedham** [comment]
Pictures all show fine. Share box works largely, calendar view is a bit of a pain if you switch months as the page jumps back down to the keyboard after every change. Also slight ui glitch with the share box overlapping the nav bar:

screenshot_2014-03-31-10-34-16

on Nexus 4.

**Comment by icewind1991** [comment]
For me the breadcrumb bar is shown in the correct possition



Both on Nexus 7 and WiPho 8

**Comment by tomneedham** [comment]
Tested on my nexus 7 and it is correct for me.

**Comment by icewind1991** [comment]
I also get the same problem with small windows on desktop chrome.

It seems to be caused by setting `position: absolute` for `#controls` while still having `top: 42px`

**Comment by jancborchardt** [comment]
@icewind1991 @tomneedham fixed the issues, please retest. :)

**Comment by jancborchardt** [comment]
Also @owncloud/designers if you’d like to test.

**Comment by icewind1991** [comment]
Tested on IE11 mobile and chrome on android :+1:

**Comment by MorrisJobke** [comment]
Works great :+1:

**Pull request merged**
