### PR TITLE
Update gallery.js

### PR DESCRIPTION
**Pull request by libasys**
JsHint says: path is out of scope so here is a better use with $.each loop

### CODE REVIEW

**Comment by jancborchardt** [comment]
@DeepDiver1975 @icewind1991 can you check this?

**Comment by icewind1991** [comment]
:-1: no reason to use jquery there, the reason "path is out of scope" is that the `var path ...` is inside the loop above, however js hoists the declaration to the top of the function.

**Comment by jancborchardt** [comment]
@icewind1991 so how to fix the JSHint issue?

**Comment by libasys** [comment]
you have to check of the object is filled and not undefined, you have to add an if cause! So my opionion the jquery $.each loop is better to use and crossbrowser friendly!

**Comment by jancborchardt** [comment]
@icewind1991 @libasys please find a consensus here then. :) cc @PVince81 for JS wizardry as well.

**Comment by PVince81** [comment]
You can also use `_.each()` which is suited to any arrays, where `$.each()` is more for jQuery arrays.

**Pull request closed without merging**
