### PR TITLE
replace logo-wide on share page with better icon + text, as in core

### PR DESCRIPTION
**Pull request by jancborchardt**
According to https://github.com/owncloud/core/pull/16517 – please review @owncloud/designers @oparoz @icewind1991 @DeepDiver1975

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please review @owncloud/designers @oparoz

**Comment by oparoz** [comment]
I'll trade you :) I review this one and you review https://github.com/owncloud/core/pull/16382 ;)

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by oparoz** [comment]
Tested, works, needs to be merged @icewind1991

**Pull request merged**
