### PR TITLE
Accessibility improvements

### PR DESCRIPTION
**Pull request by jancborchardt**
- fix accessibility of logo on public share page
- fix accessibility of slideshow navigation elements, giving them alt attributes
- fix alt texts for images and current image in slideshow
- use div instead of label on non-form element

Please review @owncloud/designers @icewind1991

### CODE REVIEW

**Comment by jancborchardt** [comment]
Some accessibility improvements for the Pictures app – ready for review @jerrac @schoeppi @lotophage @henningoschwald :)

**Comment by icewind1991** [comment]
Doesn't bread everything :+1:

**Comment by jancborchardt** [comment]
Can we have another review please @owncloud/designers  @jerrac @schoeppi @lotophage @henningoschwald? :)

**Comment by oparoz** [comment]
:+1:   as is. It works. We can decide what to do with `title` later.

**Pull request merged**
