### PR TITLE
[stable8.1] Make compatible with IE 11

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/gallery/pull/206

### CODE REVIEW

**Comment by LukasReschke** [comment]
@karlitschek THX

**Comment by DeepDiver1975** [comment]
@LukasReschke merge into master? :question:

**Comment by LukasReschke** [comment]
Blame the sangria.

**Comment by LukasReschke** [comment]
Now with the correct branch: https://github.com/owncloud/gallery/pull/208

**Pull request closed without merging**
