### PR TITLE
Rotate thumbnail when encryption is enabled

### PR DESCRIPTION
**Pull request by PVince81**
When a picture is encrypted, save it to a temporary file first so that
the PHP function for rotation can access it as file.

I'm not too thrilled about this solution as it involves temporary files.
Besides, inside the slideshow the pic is still rotated, but a recent PR that renders the slideshow with thumbnails might fix that.

Obviously I'd prefer having a library that can read directly from streams.

Such issue also exists in core for the small previews.

Let's discuss @DeepDiver1975 @georgehrke @schiesbn

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
tested - works :+1: 

But the previews in files and as a result the scaled images in the slideshow - using core's thumbnailing don't work - I'll have a look in a second pr

**Comment by PVince81** [comment]
Yes, core might need a similar workaround.

**Comment by DeepDiver1975** [comment]
> Yes, core might need a similar workaround.

here we go: https://github.com/owncloud/core/pull/8546

**Comment by icewind1991** [comment]
Code looks good :+1:

**Pull request merged**
