### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ghost**
Shameless copied from https://github.com/owncloud/calendar/pull/839

Ref: https://github.com/owncloud/core/issues/14609

### CODE REVIEW

**Comment by jospoortvliet** [comment]
pretty nice, but doesn't it make sense to mention that new development takes place in galleryplus or so?

**Comment by ghost** [comment]
Mhh, isn't this more something for: https://github.com/owncloud/gallery/blob/master/README.md

**Comment by jospoortvliet** [comment]
both I'd say. Add it to the bottom of this one, where it talks about development...

**Comment by ghost** [comment]
@jospoortvliet Done

**Comment by jospoortvliet** [comment]
:+1:

**Comment by jospoortvliet** [comment]
@oparoz you support this too I suppose? +1 and merge it then!

**Comment by oparoz** [comment]
There is already one in Gallery+ and it's not clear yet how we're going to make the switch. So best to wait. It's not like this app is going to get any fixes anyway.

**Comment by ghost** [comment]
Just merge it and do the wanted changes afterwards. Its just important to have the contributing.md in the repos which contains the basic infos. Just my humble opinion

**Comment by oparoz** [comment]
Actually, I think it would be much more useful to add a notice in this file to indicate that this project is unmaintained, that issues posted here won't be read and that users should use and report back in owncloud/galleryplus (which has a contributing.md file already). Otherwise, users make the effort of collecting all the info, only to be told that they have to use another app and report there. A bit frustrating.
It's only for a few days. We need to figure our which way forward is best: erasing everything on master or switching repo and then we can see what's missing.

**Comment by oparoz** [comment]
I just saw that there is a line at the end mentioning that new development takes place in owncloud/galleryplus. The only issue is that any problems arising in Pictures on 8.0 or 8.1 won't be fixed. That's the reason I think that this file should be solely about redirecting users to the new project. It should even be in the readme and the one-liner at the top.

**Comment by ghost** [comment]
@oparoz Ah, sorry. I wasn't aware that the switch to galleryplus is that near. Just have updated both files.

**Comment by jospoortvliet** [comment]
Let's merge this in then!

**Comment by oparoz** [comment]
Thanks @RealRancor and @jospoortvliet !

**Pull request merged**
