### PR TITLE
keep paths relative to the current user

### PR DESCRIPTION
**Pull request by schiessle**
keep paths relative to the current user, otherwise encryption will not work.

cc @PVince81 This basically works but it breaks the way we show shared galleries, maybe you can have a look at it? If I understand the code correctly all the logic should be in apps/gallery/js/gallery.js Thanks!

fix for https://github.com/owncloud/core/issues/7116

### CODE REVIEW

**Comment by karlitschek** [comment]
good catch :+1:

**Comment by icewind1991** [comment]
@schiesbn adjusted the rest of the logic to your changes, can you check if everything still works with encryption, I don't have encryption setup locally

**Comment by PVince81** [comment]
@icewind1991 I recommend you to either use multiple OC instances for testing or reset your own before every new development/test. Enabling encryption should be quite easy.

I have tested it and I get a JS error:

```
Uncaught TypeError: Cannot call method 'replace' of undefined js.js?v=2aee7f47c0321317cd6ebb336d467080:346
OC.dirname js.js?v=2aee7f47c0321317cd6ebb336d467080:346
Gallery.fillAlbums.fill gallery.js?v=2aee7f47c0321317cd6ebb336d467080:37
(anonymous function) gallery.js?v=2aee7f47c0321317cd6ebb336d467080:24
(anonymous function)
```

**Comment by PVince81** [comment]
using the steps described in https://github.com/owncloud/core/issues/7116

**Comment by icewind1991** [comment]
Fixed a problem with listing the shared albums, it now works for me with the steps from owncloud/core#7116

**Comment by schiessle** [comment]
Tested, works great! Thanks! :+1:

**Comment by PVince81** [comment]
Tested the steps from the issue with and without encryption.
Both work, but when there is a subdir, the last picture in the subdir doesn't appear (unrelated to encryption). On master it works fine.

Steps will follow.

**Comment by PVince81** [comment]
A. Subdir regression:
1. Create two users "user1" and "user2"
2. As "user1" create a folder "pics" with a subfolder "pics/subdir"
3. In"pics", upload 3 pictures.
4. In "pics/subdir" upload 5 pictures and take note what the last one looks like (mine is a burger, which is unmistakenable :wink:)
5. Share "pics" with "user2"
6. As "user2", go to the pictures app
7. Navigate to "pics", check that there are 3 pictures (correct)
8. Navigate to "pics/subdir": only 4 pictures, the last one is missing!

B. Breadcrumb regression
Use the same steps as above.
The breadcrumb is shows "Pictures", "Pictures" then "Pictures>subdir" when navigating.
On gallery/master it showed "Pictures", "Pictures>pics" then "Pictures>pics>subdir".
- [ ] fix missing pic in subdir
- [ ] fix breadcrumb regression

@icewind1991 please have a look

**Comment by icewind1991** [comment]
@PVince81 fixed both issues

**Comment by PVince81** [comment]
Works, even with encryption :+1:

**Pull request merged**
