### PR TITLE
Use closure for navigation entry

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @Raydiation

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by oparoz** [comment]
:+1:

**Comment by nickvergessen** [comment]
```
[apply] Parse error: syntax error, unexpected '[' in /home/travis/build/owncloud/gallery/appinfo/app.php on line 27
[apply] Errors parsing /home/travis/build/owncloud/gallery/appinfo/app.php
[apply] PHP Parse error: syntax error, unexpected '[' in /home/travis/build/owncloud/gallery/appinfo/app.php on line 27
```

Travis is still run with php 5.3 on stable8 and master.
But core requires 5.4 will make a PR to fix that previously.

**Comment by nickvergessen** [comment]
- [x] Depends on #177

**Pull request merged**
