### PR TITLE
Do not convert gifs when loading them fullscreen

### PR DESCRIPTION
**Pull request by oparoz**
Cute gifs to test this with
http://www.picgifs.com/graphics/kawaii-small/graphics-kawaii-small-870172-808345/

### CODE REVIEW

**Comment by oparoz** [comment]
This contribution is MIT licensed

**Comment by icewind1991** [comment]
I would prefer a single `file.mimetype === 'image/svg+xml' || file.mimetype === 'image/git'`

**Comment by oparoz** [comment]
Of course... I had them separate as I want to get rid of direct SVG rendering.

And the problem with direct rendering of Gifs is that a 4k animated cat will not be resized, but I don't think many people would be affected.

**Comment by icewind1991** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@oparoz thank you so much for fixing my cute animal animated gifs! :)

**Pull request merged**
