### PR TITLE
enhance readability of folder names

### PR DESCRIPTION
**Pull request by jancborchardt**
Use a slightly transparent darker background instead of still-hard-to-read text shadow.

Please review @libasys @icewind1991 @owncloud/designers

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by requist** [comment]
I already see 2 thumbs but I checked it out anyway, :+1: much better.

**Comment by vgezer** [comment]
@jancborchardt backport?

**Comment by jancborchardt** [comment]
@karlitschek I’d like to backport. Ok?

**Comment by karlitschek** [comment]
Yes please. Let's do an exception in this case.

**Comment by jancborchardt** [comment]
Thanks! Backported as a461fb0

**Pull request merged**
