### PR TITLE
Rotates Images in Slideshow with Encryption

### PR DESCRIPTION
**Pull request by josh4trunks**
Rotates images in slideshow based on exif data with encryption enabled.

### CODE REVIEW

**Comment by josh4trunks** [comment]
In my testing this should finish off https://github.com/owncloud/core/issues/6703

**Comment by karlitschek** [comment]
@schiesbn What do you think?

**Comment by DeepDiver1975** [comment]
@PVince81 didn't we implement this somewhere already? I'm having a Déjà-vu

**Comment by PVince81** [comment]
We might have missed this part of the gallery ?

**Comment by DeepDiver1975** [comment]
@PVince81 we fixed it there:
https://github.com/josh4trunks/gallery/blob/slideshow_rotate_encrypted/lib/thumbnail.php#L69

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@icewind1991

**Pull request merged**
